require:
  - rubocop-performance
  - rubocop-rails

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: false
  ActiveSupportExtensionsEnabled: true
  NewCops: enable

Layout/HeredocIndentation:
  Enabled: true

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Regex: !ruby/regexp /^[\w\@\-\+\.]+(\.rb)?$/

Naming/HeredocDelimiterNaming:
  ForbiddenDelimiters:
    - END, EOD, EOF

Naming/InclusiveLanguage:
  CheckStrings: true
  FlaggedTerms:
    slave:
      AllowedRegex:
        - "gitslave" # Used in formula `gitslave`
        - "log_slave" # Used in formula `ssdb`
        - "ssdb_slave" # Used in formula `ssdb`
        - "var_slave" # Used in formula `ssdb`
        - "patches/13_fix_scope_for_show_slave_status_data.patch" # Used in formula `mytop`

Naming/MethodName:
  AllowedPatterns:
    - '\A(fetch_)?HEAD\?\Z'

Naming/VariableNumber:
  Enabled: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/AutoResourceCleanup:
  Enabled: true

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/CollectionMethods:
  Enabled: true

Style/FetchEnvVar:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: annotated

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true

Style/NumericLiterals:
  MinDigits: 7
  Strict: true

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/ReturnNil:
  Enabled: true

Style/StderrPuts:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Performance/CaseWhenSplat:
  Enabled: true

Performance/Caller:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false

Rails:
  Enabled: false

Rails/ActiveSupportAliases:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/CompactBlank:
  Enabled: true

Rails/Delegate:
  Enabled: false # TODO

Rails/DelegateAllowBlank:
  Enabled: true

Rails/DurationArithmetic:
  Enabled: true

Rails/ExpandedDateRange:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/SafeNavigation:
  Enabled: true

Rails/SafeNavigationWithBlank:
  Enabled: true

Rails/StripHeredoc:
  Enabled: true

Rails/ToFormattedS:
  Enabled: true

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/ArgumentAlignment:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/SpaceAroundOperators:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

# so many of these in formulae and can't be autocorrected
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

# Most metrics don't make sense to apply for casks/formulae/taps.
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  inherit_mode:
    merge:
      - AllowedNames
  AllowedNames:
    - "a"
    - "b"
    - "cc"
    - "c1"
    - "c2"
    - "d"
    - "e"
    - "f"
    - "ff"
    - "fn"
    - "id"
    - "o"
    - "p"
    - "pr"
    - "r"
    - "rb"
    - "s"
    - "v"

# GitHub diff UI wraps beyond 118 characters
Layout/LineLength:
  Max: 118
  # ignore manpage comments and long single-line strings
  AllowedPatterns:
    [
      "#: ",
      ' url "',
      ' mirror "',
      " plist_options ",
      ' appcast "',
      ' executable: "',
      ' font "',
      ' homepage "',
      ' name "',
      ' pkg "',
      ' pkgutil: "',
      "    sha256 cellar: ",
      "    sha256  ",
      "#{language}",
      "#{version.",
      ' "/Library/Application Support/',
      '"/Library/Caches/',
      '"/Library/PreferencePanes/',
      ' "~/Library/Application Support/',
      '"~/Library/Caches/',
      '"~/Application Support',
      " was verified as official when first introduced to the cask",
    ]

Style/AccessModifierDeclarations:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/OpenStructUse:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/UnlessLogicalOperators:
  Enabled: true
  EnforcedStyle: forbid_logical_operators

Style/WordArray:
  MinSize: 4

Style/MutableConstant:
  EnforcedStyle: strict

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
